spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev # 개발 환경 ..
  redis:
    data:
      host: localhost
      port: 6379
jwt:
  secretKey: ${JWT_SECRET_KEY}
  expiration: 30
