spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # railway 서버
    url: jdbc:postgresql://${DATABASE_URL}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  profiles:
    active: dev # 개발 환경 ..
jwt:
  secretKey: ${JWT_SECRET_KEY}
  expiration: 3000
