spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatdb?useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
jwt:
  secretKey: Y2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  # secretKey : ${JWT_SECRET_KEY}
  # chatserversecretaccesstokenchatserversecretaccesstokenchatserversecretaccesstoken
  expiration: 3000 # 3000?
