spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://metro.proxy.rlwy.net:49386/?railway=false
    username: postgres
    password: rySAHDjVbXlObNlCDDkbEvbFeIkZGWys
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
jwt:
  secretKey: Y2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  # secretKey : ${JWT_SECRET_KEY}
  # chatserversecretaccesstokenchatserversecretaccesstokenchatserversecretaccesstoken
  expiration: 3000 # 3000?
